import { SocietalFactor } from './simulation';

export interface Preset {
  name: string;
  description: string;
  factors: SocietalFactor[];
  historicalOutcome?: string;
}

export const PRESETS: Preset[] = [
  {
    name: 'Balanced Society',
    description: 'A balanced society with moderate values across all factors',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 50,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 50,
        description: 'Social welfare and support programs',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 50,
        description: 'Public health and medical services',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 50,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 50,
        description: 'Public works and transportation systems',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 50,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 40,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 60,
        description: 'Press freedom and information access',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 50,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 50,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'corruption',
        name: 'Political Corruption',
        value: 30,
        description: 'Government corruption and inefficiency',
      },
      {
        id: 'social-cohesion',
        name: 'Social Cohesion',
        value: 50,
        description: 'Cultural unity and social trust',
      },
      {
        id: 'economic-inequality',
        name: 'Economic Inequality',
        value: 50,
        description: 'Wealth distribution and class divides',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 30,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 20,
        description: 'Risk of internal conflict and civil war',
      },
    ],
  },
  {
    name: 'Lower Class Focus',
    description:
      'A society focused on supporting the lower class through government aid and services',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 70,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 65,
        description: 'Social welfare and support programs',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 40,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 60,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 45,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 70,
        description: 'Public health and medical services',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 60,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 50,
        description: 'Press freedom and information access',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 60,
        description: 'Public works and transportation systems',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 40,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 40,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 30,
        description: 'Risk of internal conflict and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 15,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 10,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 10,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Middle Class Focus',
    description:
      'A society emphasizing middle class stability through education and infrastructure',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 60,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 40,
        description: 'Social welfare and support programs',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 60,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 70,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 35,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 60,
        description: 'Public health and medical services',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 50,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 70,
        description: 'Press freedom and information access',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 70,
        description: 'Public works and transportation systems',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 60,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 25,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 15,
        description: 'Risk of internal conflict and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 20,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 8,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 8,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Upper Class Focus',
    description:
      'A society prioritizing upper class wealth through business-friendly policies',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 40,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 30,
        description: 'Social welfare and support programs',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 70,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 50,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 25,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 40,
        description: 'Public health and medical services',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 30,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 80,
        description: 'Press freedom and information access',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 60,
        description: 'Public works and transportation systems',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 70,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 20,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 10,
        description: 'Risk of internal conflict and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 25,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 3,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 3,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Militant Society',
    description:
      'A society with high military spending and self-defense capabilities',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 60,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 40,
        description: 'Social welfare and support programs',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 90,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 40,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 60,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 40,
        description: 'Public health and medical services',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 30,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 20,
        description: 'Press freedom and information access',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 70,
        description: 'Public works and transportation systems',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 50,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 35,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 60,
        description: 'Risk of internal conflict and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 30,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 15,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 20,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Socialist State',
    description:
      'A society with high government control and wealth redistribution',
    factors: [
      {
        id: 'domestic-manufacturing',
        name: 'Domestic Manufacturing',
        value: 80,
        description: 'Affects job creation and economic independence',
      },
      {
        id: 'government-aid',
        name: 'Government Aid',
        value: 85,
        description: 'Social welfare and support programs',
      },
      {
        id: 'self-defense',
        name: 'Self-Defense Freedom',
        value: 30,
        description: 'Personal security and civil liberties',
      },
      {
        id: 'education',
        name: 'Education Funding',
        value: 80,
        description: 'Access to quality education and skill development',
      },
      {
        id: 'tax-rate',
        name: 'Tax Rate',
        value: 70,
        description: 'Government revenue and wealth distribution',
      },
      {
        id: 'healthcare',
        name: 'Healthcare Access',
        value: 85,
        description: 'Public health and medical services',
      },
      {
        id: 'environmental-protection',
        name: 'Environmental Protection',
        value: 70,
        description: 'Environmental regulations and sustainability',
      },
      {
        id: 'media-freedom',
        name: 'Media Freedom',
        value: 30,
        description: 'Press freedom and information access',
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure Investment',
        value: 60,
        description: 'Public works and transportation systems',
      },
      {
        id: 'research-development',
        name: 'Research & Development',
        value: 40,
        description: 'Scientific advancement and innovation',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 30,
        description: 'Frequency and severity of natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 40,
        description: 'Risk of internal conflict and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 15,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 12,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 15,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Great Depression',
    description:
      'USA, 1929-1939: Economic collapse with minimal government intervention',
    historicalOutcome:
      'Breadlines form as factories close, unemployment reaches 25%, and public health deteriorates. The New Deal later brings some relief but recovery remains slow.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 20,
        name: 'Domestic Manufacturing',
        description: 'Massive decline in industrial output',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Initially minimal government intervention',
      },
      {
        id: 'healthcare',
        value: 15,
        name: 'Healthcare',
        description: 'Limited access due to economic collapse',
      },
      {
        id: 'education',
        value: 20,
        name: 'Education',
        description: 'Budget cuts for public education',
      },
      {
        id: 'infrastructure',
        value: 25,
        name: 'Infrastructure',
        description: 'Lack of public works until New Deal',
      },
      {
        id: 'environmental-protection',
        value: 5,
        name: 'Environmental Protection',
        description: 'Little focus on environment during hardship',
      },
      {
        id: 'tax-rate',
        value: 20,
        name: 'Tax Rate',
        description: 'Low initially, increased later with New Deal',
      },
      {
        id: 'media-freedom',
        value: 70,
        name: 'Media Freedom',
        description: 'Relatively free press, critical of government',
      },
      {
        id: 'self-defense',
        value: 50,
        name: 'Self-Defense',
        description: 'Moderate; no major militia activity',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'Minimal innovation funding during crisis',
      },
      {
        id: 'corruption',
        value: 30,
        name: 'Political Corruption',
        description: 'Moderate corruption during recovery efforts',
      },
      {
        id: 'social-cohesion',
        value: 40,
        name: 'Social Cohesion',
        description: 'High inequality, moderate unrest',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme wealth concentration',
      },
      {
        id: 'gender-equality',
        value: 20,
        name: 'Gender Equality',
        description: 'Limited opportunities for women in workforce',
      },
      {
        id: 'child-labor',
        value: 40,
        name: 'Child Labor',
        description: 'Children working to support families',
      },
      {
        id: 'religious-influence',
        value: 50,
        name: 'Religious Influence',
        description: 'Moderate religious influence during crisis',
      },
      {
        id: 'technological-adoption',
        value: 30,
        name: 'Technological Adoption',
        description: 'Stagnant technological progress',
      },
      {
        id: 'immigration-rate',
        value: 10,
        name: 'Immigration Rate',
        description: 'Restricted immigration during crisis',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 60,
        description: 'Dust Bowl and environmental disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 40,
        description: 'Risk of civil unrest and violence',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 5,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 10,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 5,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Collapse of Venezuela',
    description: '2010s-2020s: Economic mismanagement and social crisis',
    historicalOutcome:
      'Hyperinflation, food shortages, and mass emigration. Despite high government aid promises, corruption and mismanagement lead to widespread suffering.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 10,
        name: 'Domestic Manufacturing',
        description: 'Heavy reliance on imports, collapsed local production',
      },
      {
        id: 'government-aid',
        value: 80,
        name: 'Government Aid',
        description:
          'High aid promised but often ineffective due to corruption',
      },
      {
        id: 'healthcare',
        value: 5,
        name: 'Healthcare',
        description: 'Severe shortages of medical supplies',
      },
      {
        id: 'education',
        value: 10,
        name: 'Education',
        description: 'Massive brain drain and school closures',
      },
      {
        id: 'infrastructure',
        value: 5,
        name: 'Infrastructure',
        description: 'Power outages, crumbling roads',
      },
      {
        id: 'environmental-protection',
        value: 5,
        name: 'Environmental Protection',
        description: 'Oil spills, deforestation ignored',
      },
      {
        id: 'tax-rate',
        value: 40,
        name: 'Tax Rate',
        description: 'High taxes but mismanaged revenue',
      },
      {
        id: 'media-freedom',
        value: 10,
        name: 'Media Freedom',
        description: 'Heavy censorship and state control',
      },
      {
        id: 'self-defense',
        value: 80,
        name: 'Self-Defense',
        description: 'High crime rates, militias, and citizen arming',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'Little focus on innovation',
      },
      {
        id: 'corruption',
        value: 90,
        name: 'Political Corruption',
        description: 'Rampant corruption is a key driver',
      },
      {
        id: 'social-cohesion',
        value: 10,
        name: 'Social Cohesion',
        description: 'Extreme social divides',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme wealth concentration',
      },
      {
        id: 'gender-equality',
        value: 30,
        name: 'Gender Equality',
        description: 'Women disproportionately affected by crisis',
      },
      {
        id: 'child-labor',
        value: 20,
        name: 'Child Labor',
        description: 'Some children working in informal sector',
      },
      {
        id: 'religious-influence',
        value: 40,
        name: 'Religious Influence',
        description: 'Religious organizations providing aid',
      },
      {
        id: 'technological-adoption',
        value: 20,
        name: 'Technological Adoption',
        description: 'Limited technological progress',
      },
      {
        id: 'immigration-rate',
        value: 5,
        name: 'Immigration Rate',
        description: 'Mass emigration rather than immigration',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 40,
        description: 'Environmental and infrastructure failures',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 70,
        description: 'High risk of civil conflict',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 30,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 20,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 10,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'French Revolution',
    description: 'France, 1789-1799: Inequality and revolutionary violence',
    historicalOutcome:
      'Widespread poverty and inequality lead to revolutionary violence. The monarchy falls, but the new republic faces internal conflict and external threats.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Agricultural economy, limited industrial base',
      },
      {
        id: 'government-aid',
        value: 5,
        name: 'Government Aid',
        description: 'Minimal support for lower classes pre-revolution',
      },
      {
        id: 'healthcare',
        value: 10,
        name: 'Healthcare',
        description: 'Poor public health systems',
      },
      {
        id: 'education',
        value: 15,
        name: 'Education',
        description: 'Limited access, mostly for elites',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Poor roads, urban squalor',
      },
      {
        id: 'environmental-protection',
        value: 5,
        name: 'Environmental Protection',
        description: 'No focus on environment',
      },
      {
        id: 'tax-rate',
        value: 70,
        name: 'Tax Rate',
        description: 'High taxes on peasants, low on nobility',
      },
      {
        id: 'media-freedom',
        value: 30,
        name: 'Media Freedom',
        description: 'Censorship pre-revolution, some freedom during',
      },
      {
        id: 'self-defense',
        value: 90,
        name: 'Self-Defense',
        description: 'Armed militias, revolutionary violence',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'Limited innovation during turmoil',
      },
      {
        id: 'corruption',
        value: 70,
        name: 'Political Corruption',
        description: 'Aristocratic privilege and tax mismanagement',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Deep class divides drove revolution',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme class divides',
      },
      {
        id: 'gender-equality',
        value: 10,
        name: 'Gender Equality',
        description: 'Extreme gender inequality, women excluded from power',
      },
      {
        id: 'child-labor',
        value: 30,
        name: 'Child Labor',
        description: 'Children working in agriculture and crafts',
      },
      {
        id: 'religious-influence',
        value: 80,
        name: 'Religious Influence',
        description: 'Strong Catholic Church influence, later suppressed',
      },
      {
        id: 'technological-adoption',
        value: 10,
        name: 'Technological Adoption',
        description: 'Pre-industrial technology',
      },
      {
        id: 'immigration-rate',
        value: 20,
        name: 'Immigration Rate',
        description: 'Limited immigration during revolution',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 50,
        description: 'Crop failures and natural disasters',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 90,
        description: 'Revolutionary violence and civil war',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 20,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 10,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 5,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Industrial Revolution',
    description:
      'Britain, 1760-1840: Rapid industrialization and social change',
    historicalOutcome:
      'Massive economic growth but with severe social costs. Urban slums form, child labor is widespread, and environmental damage is extensive.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 90,
        name: 'Domestic Manufacturing',
        description: 'Massive industrial growth',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Little welfare for workers',
      },
      {
        id: 'healthcare',
        value: 15,
        name: 'Healthcare',
        description: 'Poor health conditions in factories',
      },
      {
        id: 'education',
        value: 20,
        name: 'Education',
        description: 'Limited public education, child labor common',
      },
      {
        id: 'infrastructure',
        value: 60,
        name: 'Infrastructure',
        description: 'Investment in canals, railways',
      },
      {
        id: 'environmental-protection',
        value: 5,
        name: 'Environmental Protection',
        description: 'Heavy pollution, no regulation',
      },
      {
        id: 'tax-rate',
        value: 30,
        name: 'Tax Rate',
        description: 'Moderate taxes to fund wars and growth',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Some press freedom, but restricted',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Moderate; no major militias',
      },
      {
        id: 'research-development',
        value: 80,
        name: 'Research & Development',
        description: 'Innovation in machinery, textiles',
      },
      {
        id: 'corruption',
        value: 40,
        name: 'Political Corruption',
        description: 'Some factory owner collusion but not systemic',
      },
      {
        id: 'social-cohesion',
        value: 30,
        name: 'Social Cohesion',
        description: 'Factory workers vs. owners',
      },
      {
        id: 'economic-inequality',
        value: 70,
        name: 'Economic Inequality',
        description: 'Growing class divides',
      },
      {
        id: 'gender-equality',
        value: 15,
        name: 'Gender Equality',
        description: 'Women and children exploited in factories',
      },
      {
        id: 'child-labor',
        value: 80,
        name: 'Child Labor',
        description: 'Widespread child labor in factories',
      },
      {
        id: 'religious-influence',
        value: 60,
        name: 'Religious Influence',
        description: 'Strong religious influence, some reform movements',
      },
      {
        id: 'technological-adoption',
        value: 90,
        name: 'Technological Adoption',
        description: 'Rapid technological innovation',
      },
      {
        id: 'immigration-rate',
        value: 70,
        name: 'Immigration Rate',
        description: 'High rural to urban migration',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 30,
        description: 'Industrial accidents and pollution',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 20,
        description: 'Labor unrest and protests',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 10,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 5,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 5,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Fall of Soviet Union',
    description: 'USSR, 1989-1991: Systemic collapse and transition',
    historicalOutcome:
      'Economic collapse, political turmoil, and social upheaval. The transition to capitalism brings both opportunity and hardship.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Declining industrial output',
      },
      {
        id: 'government-aid',
        value: 70,
        name: 'Government Aid',
        description: 'High but ineffective state support',
      },
      {
        id: 'healthcare',
        value: 20,
        name: 'Healthcare',
        description: 'Deteriorating public health systems',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Still some access, but quality fell',
      },
      {
        id: 'infrastructure',
        value: 25,
        name: 'Infrastructure',
        description: 'Aging Soviet infrastructure',
      },
      {
        id: 'environmental-protection',
        value: 10,
        name: 'Environmental Protection',
        description: 'Major disasters like Chernobyl',
      },
      {
        id: 'tax-rate',
        value: 60,
        name: 'Tax Rate',
        description: 'High taxes, but mismanaged',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'State-controlled, some glasnost reforms',
      },
      {
        id: 'self-defense',
        value: 70,
        name: 'Self-Defense',
        description: 'Rising crime, weakened state control',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Declining scientific funding',
      },
      {
        id: 'corruption',
        value: 80,
        name: 'Political Corruption',
        description: 'Widespread corruption in late Soviet bureaucracy',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Growing divides, black markets',
      },
      {
        id: 'economic-inequality',
        value: 60,
        name: 'Economic Inequality',
        description: 'Growing wealth gaps',
      },
      {
        id: 'gender-equality',
        value: 40,
        name: 'Gender Equality',
        description: 'Soviet gender equality declines in transition',
      },
      {
        id: 'child-labor',
        value: 10,
        name: 'Child Labor',
        description: 'Low child labor, education still valued',
      },
      {
        id: 'religious-influence',
        value: 10,
        name: 'Religious Influence',
        description: 'Post-atheist religious revival',
      },
      {
        id: 'technological-adoption',
        value: 30,
        name: 'Technological Adoption',
        description: 'Military tech transfer to civilian sector',
      },
      {
        id: 'immigration-rate',
        value: 5,
        name: 'Immigration Rate',
        description: 'Emigration rather than immigration',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 30,
        description: 'Environmental disasters like Chernobyl',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 60,
        description: 'Risk of civil war and ethnic conflicts',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 20,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 15,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 5,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
  {
    name: 'Post-WWII Boom',
    description: 'USA, 1945-1970: Economic prosperity and social progress',
    historicalOutcome:
      'Unprecedented economic growth, rising middle class, and technological innovation. Social programs expand and infrastructure modernizes.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 90,
        name: 'Domestic Manufacturing',
        description: 'Industrial powerhouse',
      },
      {
        id: 'government-aid',
        value: 60,
        name: 'Government Aid',
        description: 'GI Bill, welfare programs',
      },
      {
        id: 'healthcare',
        value: 70,
        name: 'Healthcare',
        description: 'Improved access, rise of modern medicine',
      },
      {
        id: 'education',
        value: 80,
        name: 'Education',
        description: 'Expanded public education, college access',
      },
      {
        id: 'infrastructure',
        value: 90,
        name: 'Infrastructure',
        description: 'Highway system, suburban growth',
      },
      {
        id: 'environmental-protection',
        value: 30,
        name: 'Environmental Protection',
        description: 'Some regulation, pre-EPA',
      },
      {
        id: 'tax-rate',
        value: 50,
        name: 'Tax Rate',
        description: 'High taxes to fund growth',
      },
      {
        id: 'media-freedom',
        value: 80,
        name: 'Media Freedom',
        description: 'Free press, booming media',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Stable, no major militias',
      },
      {
        id: 'research-development',
        value: 90,
        name: 'Research & Development',
        description: 'Space race, tech innovation',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Relatively low due to strong institutions',
      },
      {
        id: 'social-cohesion',
        value: 80,
        name: 'Social Cohesion',
        description: 'Unity and growing middle class',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Reduced inequality, strong middle class',
      },
      {
        id: 'gender-equality',
        value: 50,
        name: 'Gender Equality',
        description: 'Women entering workforce, but still unequal',
      },
      {
        id: 'child-labor',
        value: 5,
        name: 'Child Labor',
        description: 'Strong child labor laws',
      },
      {
        id: 'religious-influence',
        value: 40,
        name: 'Religious Influence',
        description: 'Moderate religious influence, secularizing',
      },
      {
        id: 'technological-adoption',
        value: 90,
        name: 'Technological Adoption',
        description: 'Rapid technological progress',
      },
      {
        id: 'immigration-rate',
        value: 60,
        name: 'Immigration Rate',
        description: 'High immigration for labor needs',
      },
      {
        id: 'natural-disaster-frequency',
        name: 'Natural Disaster Frequency',
        value: 20,
        description: 'Relatively stable period',
      },
      {
        id: 'domestic-war-risk',
        name: 'Domestic War Risk',
        value: 10,
        description: 'Low risk of internal conflict',
      },
      {
        id: 'mana-storm-intensity',
        name: 'Mana Storm Intensity',
        value: 10,
        description: 'Intensity of magical energy disturbances',
      },
      {
        id: 'thanos-snap-probability',
        name: 'Thanos Snap Probability',
        value: 5,
        description: 'Probability of half the population disappearing',
      },
      {
        id: 'godzilla-rampage',
        name: 'Godzilla Rampage',
        value: 5,
        description: 'Likelihood of giant monster attacks',
      },
    ],
  },
];

export interface HistoricalPreset {
  name: string;
  description: string;
  factors: Record<string, number>;
  color: string;
}

export const HISTORICAL_PRESETS: HistoricalPreset[] = [
  {
    name: 'Industrial Revolution',
    description:
      'Rapid industrialization with high pollution and social inequality',
    factors: {
      'domestic-manufacturing': 90,
      'government-aid': 20,
      healthcare: 30,
      education: 40,
      infrastructure: 70,
      'environmental-protection': 10,
      'tax-rate': 30,
      'media-freedom': 40,
      'self-defense': 60,
      'research-development': 80,
      corruption: 50,
      'social-cohesion': 40,
      'economic-inequality': 80,
      'technological-adoption': 90,
      'immigration-rate': 60,
      'natural-disaster-frequency': 30,
      'domestic-war-risk': 20,
    },
    color: '#FF6B6B',
  },
  {
    name: 'French Revolution',
    description: 'Social upheaval and political instability',
    factors: {
      'domestic-manufacturing': 40,
      'government-aid': 30,
      healthcare: 30,
      education: 50,
      infrastructure: 40,
      'environmental-protection': 20,
      'tax-rate': 70,
      'media-freedom': 60,
      'self-defense': 80,
      'research-development': 40,
      corruption: 70,
      'social-cohesion': 20,
      'economic-inequality': 80,
      'technological-adoption': 40,
      'immigration-rate': 30,
      'natural-disaster-frequency': 20,
      'domestic-war-risk': 90,
    },
    color: '#4ECDC4',
  },
  {
    name: 'Post-WWII Boom',
    description: 'Economic growth and social welfare expansion',
    factors: {
      'domestic-manufacturing': 80,
      'government-aid': 70,
      healthcare: 70,
      education: 80,
      infrastructure: 80,
      'environmental-protection': 40,
      'tax-rate': 50,
      'media-freedom': 70,
      'self-defense': 60,
      'research-development': 70,
      corruption: 30,
      'social-cohesion': 70,
      'economic-inequality': 40,
      'technological-adoption': 90,
      'immigration-rate': 50,
      'natural-disaster-frequency': 20,
      'domestic-war-risk': 10,
      'mana-storm-intensity': 10,
      'thanos-snap-probability': 5,
      'godzilla-rampage': 5,
    },
    color: '#45B7D1',
  },
  {
    name: 'Collapse of Venezuela',
    description: 'Economic collapse and social unrest',
    factors: {
      'domestic-manufacturing': 20,
      'government-aid': 30,
      healthcare: 20,
      education: 30,
      infrastructure: 30,
      'environmental-protection': 40,
      'tax-rate': 60,
      'media-freedom': 20,
      'self-defense': 40,
      'research-development': 20,
      corruption: 90,
      'social-cohesion': 20,
      'economic-inequality': 90,
      'technological-adoption': 30,
      'immigration-rate': 5,
      'natural-disaster-frequency': 40,
      'domestic-war-risk': 70,
      'mana-storm-intensity': 30,
      'thanos-snap-probability': 20,
      'godzilla-rampage': 10,
    },
    color: '#96CEB4',
  },
  {
    name: 'Fall of the Soviet Union',
    description: 'Political collapse and economic transition',
    factors: {
      'domestic-manufacturing': 40,
      'government-aid': 30,
      healthcare: 30,
      education: 50,
      infrastructure: 40,
      'environmental-protection': 20,
      'tax-rate': 50,
      'media-freedom': 60,
      'self-defense': 40,
      'research-development': 40,
      corruption: 80,
      'social-cohesion': 30,
      'economic-inequality': 70,
      'technological-adoption': 50,
      'immigration-rate': 40,
      'natural-disaster-frequency': 30,
      'domestic-war-risk': 60,
      'mana-storm-intensity': 20,
      'thanos-snap-probability': 15,
      'godzilla-rampage': 5,
    },
    color: '#FFEEAD',
  },
];

export const PRESET_COLORS = {
  'Industrial Revolution': '#FF6B6B',
  'French Revolution': '#4ECDC4',
  'Post-WWII Boom': '#45B7D1',
  'Collapse of Venezuela': '#96CEB4',
  'Fall of the Soviet Union': '#FFEEAD',
};
