import { SocietalFactor } from './simulation';

export interface Preset {
  name: string;
  description: string;
  factors: SocietalFactor[];
  historicalOutcome?: string;
  color: string;
}

export const PRESETS: Preset[] = [
  // Basic Scenarios
  {
    name: 'Anarchic Society',
    description: 'Freedom over order, low governance',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Limited organized production',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Minimal government intervention',
      },
      {
        id: 'self-defense',
        value: 90,
        name: 'Self-Defense',
        description: 'High personal responsibility',
      },
      {
        id: 'education',
        value: 30,
        name: 'Education',
        description: 'Decentralized learning',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Basic community structures',
      },
      {
        id: 'social-cohesion',
        value: 60,
        name: 'Social Cohesion',
        description: 'Strong community bonds',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Moderate wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 90,
        name: 'Media Freedom',
        description: 'Unrestricted information flow',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Community-driven innovation',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Minimal corruption risk',
      },
      {
        id: 'natural-disaster-frequency',
        value: 50,
        name: 'Natural Disaster Frequency',
        description: 'Community resilience',
      },
      {
        id: 'domestic-war-risk',
        value: 40,
        name: 'Domestic War Risk',
        description: 'Localized conflicts',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Viking Society',
    description: 'Warrior culture, high cohesion',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 70,
        name: 'Domestic Manufacturing',
        description: 'Strong local production',
      },
      {
        id: 'self-defense',
        value: 90,
        name: 'Self-Defense',
        description: 'Warrior culture',
      },
      {
        id: 'social-cohesion',
        value: 80,
        name: 'Social Cohesion',
        description: 'Strong community bonds',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Practical skills focus',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Community support',
      },
      {
        id: 'religious-influence',
        value: 70,
        name: 'Religious Influence',
        description: 'Strong cultural influence',
      },
      {
        id: 'infrastructure',
        value: 50,
        name: 'Infrastructure',
        description: 'Basic but functional',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Moderate wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Oral tradition',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Practical innovation',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Environmental challenges',
      },
      {
        id: 'domestic-war-risk',
        value: 30,
        name: 'Domestic War Risk',
        description: 'Internal stability',
      },
    ],
    color: '#4ECDC4',
  },
  {
    name: 'Barter Society',
    description: 'No currency, trade-based',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 60,
        name: 'Domestic Manufacturing',
        description: 'Local production focus',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Minimal intervention',
      },
      {
        id: 'self-defense',
        value: 50,
        name: 'Self-Defense',
        description: 'Community protection',
      },
      {
        id: 'education',
        value: 30,
        name: 'Education',
        description: 'Practical skills',
      },
      {
        id: 'infrastructure',
        value: 40,
        name: 'Infrastructure',
        description: 'Basic trade routes',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'Strong trade networks',
      },
      {
        id: 'economic-inequality',
        value: 30,
        name: 'Economic Inequality',
        description: 'Moderate wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 50,
        name: 'Media Freedom',
        description: 'Trade information',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Environmental impact',
      },
      {
        id: 'domestic-war-risk',
        value: 30,
        name: 'Domestic War Risk',
        description: 'Trade disputes',
      },
    ],
    color: '#45B7D1',
  },
  {
    name: 'Feudal Society',
    description: 'Hierarchical, low mobility',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Agricultural focus',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Minimal support',
      },
      {
        id: 'self-defense',
        value: 70,
        name: 'Self-Defense',
        description: 'Noble protection',
      },
      {
        id: 'education',
        value: 20,
        name: 'Education',
        description: 'Elite education',
      },
      {
        id: 'infrastructure',
        value: 30,
        name: 'Infrastructure',
        description: 'Basic roads',
      },
      {
        id: 'social-cohesion',
        value: 40,
        name: 'Social Cohesion',
        description: 'Class divides',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'Controlled information',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 60,
        name: 'Political Corruption',
        description: 'Noble privilege',
      },
      {
        id: 'natural-disaster-frequency',
        value: 50,
        name: 'Natural Disaster Frequency',
        description: 'Agricultural impact',
      },
      {
        id: 'domestic-war-risk',
        value: 40,
        name: 'Domestic War Risk',
        description: 'Noble conflicts',
      },
    ],
    color: '#96CEB4',
  },
  {
    name: 'Technocratic Society',
    description: 'Tech-driven, high R&D',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 80,
        name: 'Domestic Manufacturing',
        description: 'Advanced production',
      },
      {
        id: 'government-aid',
        value: 40,
        name: 'Government Aid',
        description: 'Tech support',
      },
      {
        id: 'self-defense',
        value: 60,
        name: 'Self-Defense',
        description: 'Tech security',
      },
      {
        id: 'education',
        value: 90,
        name: 'Education',
        description: 'STEM focus',
      },
      {
        id: 'infrastructure',
        value: 80,
        name: 'Infrastructure',
        description: 'Advanced systems',
      },
      {
        id: 'social-cohesion',
        value: 50,
        name: 'Social Cohesion',
        description: 'Tech integration',
      },
      {
        id: 'economic-inequality',
        value: 60,
        name: 'Economic Inequality',
        description: 'Tech divide',
      },
      {
        id: 'media-freedom',
        value: 70,
        name: 'Media Freedom',
        description: 'Digital access',
      },
      {
        id: 'research-development',
        value: 90,
        name: 'Research & Development',
        description: 'High innovation',
      },
      {
        id: 'corruption',
        value: 30,
        name: 'Political Corruption',
        description: 'Tech oversight',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Tech mitigation',
      },
      {
        id: 'domestic-war-risk',
        value: 20,
        name: 'Domestic War Risk',
        description: 'Tech stability',
      },
    ],
    color: '#FFEEAD',
  },
  {
    name: 'Nomadic Society',
    description: 'Mobile, low infrastructure',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Portable goods',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Community support',
      },
      {
        id: 'self-defense',
        value: 70,
        name: 'Self-Defense',
        description: 'Mobile defense',
      },
      {
        id: 'education',
        value: 30,
        name: 'Education',
        description: 'Oral tradition',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Minimal fixed structures',
      },
      {
        id: 'social-cohesion',
        value: 80,
        name: 'Social Cohesion',
        description: 'Strong bonds',
      },
      {
        id: 'economic-inequality',
        value: 30,
        name: 'Economic Inequality',
        description: 'Shared resources',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Oral communication',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Traditional knowledge',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Environmental adaptation',
      },
      {
        id: 'domestic-war-risk',
        value: 30,
        name: 'Domestic War Risk',
        description: 'Territorial disputes',
      },
    ],
    color: '#FFB6C1',
  },
  {
    name: 'Balanced Society',
    description: 'Equal class prosperity',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 60,
        name: 'Domestic Manufacturing',
        description: 'Stable production',
      },
      {
        id: 'government-aid',
        value: 50,
        name: 'Government Aid',
        description: 'Moderate support',
      },
      {
        id: 'self-defense',
        value: 50,
        name: 'Self-Defense',
        description: 'Balanced security',
      },
      {
        id: 'education',
        value: 70,
        name: 'Education',
        description: 'Universal access',
      },
      {
        id: 'infrastructure',
        value: 60,
        name: 'Infrastructure',
        description: 'Well-maintained',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'Strong unity',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Moderate gaps',
      },
      {
        id: 'media-freedom',
        value: 70,
        name: 'Media Freedom',
        description: 'Free press',
      },
      {
        id: 'research-development',
        value: 60,
        name: 'Research & Development',
        description: 'Steady innovation',
      },
      {
        id: 'corruption',
        value: 30,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Managed risk',
      },
      {
        id: 'domestic-war-risk',
        value: 20,
        name: 'Domestic War Risk',
        description: 'Low conflict',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Lower Class Focus',
    description: 'High aid, low inequality',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 70,
        name: 'Domestic Manufacturing',
        description: 'Job creation focus',
      },
      {
        id: 'government-aid',
        value: 80,
        name: 'Government Aid',
        description: 'Strong support',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Community security',
      },
      {
        id: 'education',
        value: 70,
        name: 'Education',
        description: 'Universal access',
      },
      {
        id: 'infrastructure',
        value: 60,
        name: 'Infrastructure',
        description: 'Public services',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'Strong community',
      },
      {
        id: 'economic-inequality',
        value: 30,
        name: 'Economic Inequality',
        description: 'Reduced gaps',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Public voice',
      },
      {
        id: 'research-development',
        value: 40,
        name: 'Research & Development',
        description: 'Basic innovation',
      },
      {
        id: 'corruption',
        value: 30,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Community resilience',
      },
      {
        id: 'domestic-war-risk',
        value: 30,
        name: 'Domestic War Risk',
        description: 'Low conflict',
      },
    ],
    color: '#4ECDC4',
  },
  {
    name: 'Middle Class Focus',
    description: 'High stability, moderate tax',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 70,
        name: 'Domestic Manufacturing',
        description: 'Stable production',
      },
      {
        id: 'government-aid',
        value: 40,
        name: 'Government Aid',
        description: 'Moderate support',
      },
      {
        id: 'self-defense',
        value: 60,
        name: 'Self-Defense',
        description: 'Personal security',
      },
      {
        id: 'education',
        value: 80,
        name: 'Education',
        description: 'Quality access',
      },
      {
        id: 'infrastructure',
        value: 70,
        name: 'Infrastructure',
        description: 'Well-maintained',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'Strong unity',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Moderate gaps',
      },
      {
        id: 'media-freedom',
        value: 70,
        name: 'Media Freedom',
        description: 'Free press',
      },
      {
        id: 'research-development',
        value: 60,
        name: 'Research & Development',
        description: 'Steady innovation',
      },
      {
        id: 'corruption',
        value: 30,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Managed risk',
      },
      {
        id: 'domestic-war-risk',
        value: 20,
        name: 'Domestic War Risk',
        description: 'Low conflict',
      },
    ],
    color: '#45B7D1',
  },
  {
    name: 'Upper Class Focus',
    description: 'High inequality, low aid',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Luxury focus',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Minimal support',
      },
      {
        id: 'self-defense',
        value: 80,
        name: 'Self-Defense',
        description: 'Private security',
      },
      {
        id: 'education',
        value: 60,
        name: 'Education',
        description: 'Elite access',
      },
      {
        id: 'infrastructure',
        value: 50,
        name: 'Infrastructure',
        description: 'Private focus',
      },
      {
        id: 'social-cohesion',
        value: 30,
        name: 'Social Cohesion',
        description: 'Class divides',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme gaps',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Controlled press',
      },
      {
        id: 'research-development',
        value: 70,
        name: 'Research & Development',
        description: 'Elite innovation',
      },
      {
        id: 'corruption',
        value: 60,
        name: 'Political Corruption',
        description: 'High corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Protected areas',
      },
      {
        id: 'domestic-war-risk',
        value: 40,
        name: 'Domestic War Risk',
        description: 'Class conflict',
      },
    ],
    color: '#FFEEAD',
  },
  {
    name: 'Militant Society',
    description: 'High self-defense, moderate cohesion',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 70,
        name: 'Domestic Manufacturing',
        description: 'Military focus',
      },
      {
        id: 'government-aid',
        value: 30,
        name: 'Government Aid',
        description: 'Military support',
      },
      {
        id: 'self-defense',
        value: 90,
        name: 'Self-Defense',
        description: 'Strong military',
      },
      {
        id: 'education',
        value: 50,
        name: 'Education',
        description: 'Military training',
      },
      {
        id: 'infrastructure',
        value: 70,
        name: 'Infrastructure',
        description: 'Military focus',
      },
      {
        id: 'social-cohesion',
        value: 60,
        name: 'Social Cohesion',
        description: 'Military unity',
      },
      {
        id: 'economic-inequality',
        value: 50,
        name: 'Economic Inequality',
        description: 'Military hierarchy',
      },
      {
        id: 'media-freedom',
        value: 30,
        name: 'Media Freedom',
        description: 'Military control',
      },
      {
        id: 'research-development',
        value: 70,
        name: 'Research & Development',
        description: 'Military innovation',
      },
      {
        id: 'corruption',
        value: 40,
        name: 'Political Corruption',
        description: 'Military oversight',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Military response',
      },
      {
        id: 'domestic-war-risk',
        value: 40,
        name: 'Domestic War Risk',
        description: 'Military tension',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Socialist State',
    description: 'High aid, low inequality, centralized control',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 80,
        name: 'Domestic Manufacturing',
        description: 'State control',
      },
      {
        id: 'government-aid',
        value: 90,
        name: 'Government Aid',
        description: 'Universal support',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'State security',
      },
      {
        id: 'education',
        value: 80,
        name: 'Education',
        description: 'Universal access',
      },
      {
        id: 'infrastructure',
        value: 70,
        name: 'Infrastructure',
        description: 'Public focus',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'State unity',
      },
      {
        id: 'economic-inequality',
        value: 20,
        name: 'Economic Inequality',
        description: 'Minimal gaps',
      },
      {
        id: 'media-freedom',
        value: 30,
        name: 'Media Freedom',
        description: 'State control',
      },
      {
        id: 'research-development',
        value: 50,
        name: 'Research & Development',
        description: 'State innovation',
      },
      {
        id: 'corruption',
        value: 60,
        name: 'Political Corruption',
        description: 'Bureaucratic issues',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'State response',
      },
      {
        id: 'domestic-war-risk',
        value: 30,
        name: 'Domestic War Risk',
        description: 'State control',
      },
    ],
    color: '#D4A5A5',
  },
  // Historical Scenarios
  {
    name: 'Pre-Revolutionary Iran',
    description: 'Modernization fails, revolution',
    historicalOutcome:
      "Failed modernization attempts and growing social tensions lead to the Islamic Revolution, transforming Iran's political and social landscape.",
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Limited industrialization',
      },
      {
        id: 'government-aid',
        value: 30,
        name: 'Government Aid',
        description: 'Corrupt distribution',
      },
      {
        id: 'self-defense',
        value: 60,
        name: 'Self-Defense',
        description: 'Revolutionary groups',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Uneven access',
      },
      {
        id: 'infrastructure',
        value: 50,
        name: 'Infrastructure',
        description: 'Urban-rural divide',
      },
      {
        id: 'social-cohesion',
        value: 30,
        name: 'Social Cohesion',
        description: 'Deep cultural divides',
      },
      {
        id: 'economic-inequality',
        value: 70,
        name: 'Economic Inequality',
        description: 'Growing wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 40,
        name: 'Media Freedom',
        description: 'State control',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 80,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Moderate risk',
      },
      {
        id: 'domestic-war-risk',
        value: 70,
        name: 'Domestic War Risk',
        description: 'High revolution risk',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Weimar Republic',
    description: 'Economic ruin, authoritarian rise',
    historicalOutcome:
      'Economic collapse, political instability, and social unrest create conditions for the rise of authoritarianism and the Nazi dictatorship.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Economic collapse',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Failed support',
      },
      {
        id: 'self-defense',
        value: 70,
        name: 'Self-Defense',
        description: 'Paramilitary groups',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Declining quality',
      },
      {
        id: 'infrastructure',
        value: 30,
        name: 'Infrastructure',
        description: 'Neglected',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Deep divides',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme poverty',
      },
      {
        id: 'media-freedom',
        value: 50,
        name: 'Media Freedom',
        description: 'Propaganda rise',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 70,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Moderate risk',
      },
      {
        id: 'domestic-war-risk',
        value: 80,
        name: 'Domestic War Risk',
        description: 'High unrest',
      },
    ],
    color: '#4ECDC4',
  },
  {
    name: 'Pre-Civil War America',
    description: 'Slavery split, war looms',
    historicalOutcome:
      'Deepening divide over slavery, economic differences between North and South, and political polarization lead to the deadliest conflict in American history.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 70,
        name: 'Domestic Manufacturing',
        description: 'Industrial North',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Limited federal role',
      },
      {
        id: 'self-defense',
        value: 70,
        name: 'Self-Defense',
        description: 'Armed militias',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Uneven access',
      },
      {
        id: 'infrastructure',
        value: 60,
        name: 'Infrastructure',
        description: 'Railroad expansion',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Deep sectional divide',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Slavery and class divide',
      },
      {
        id: 'media-freedom',
        value: 80,
        name: 'Media Freedom',
        description: 'Free but partisan press',
      },
      {
        id: 'research-development',
        value: 40,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 50,
        name: 'Political Corruption',
        description: 'Sectional politics',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Moderate risk',
      },
      {
        id: 'domestic-war-risk',
        value: 90,
        name: 'Domestic War Risk',
        description: 'Imminent civil war',
      },
    ],
    color: '#45B7D1',
  },
  {
    name: 'Pre-Communist China',
    description: 'Chaos, Communist victory',
    historicalOutcome:
      "Widespread poverty, civil war, and social unrest create conditions for the Communist Party's rise to power and the establishment of the People's Republic of China.",
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'War-torn economy',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Failed state',
      },
      {
        id: 'self-defense',
        value: 80,
        name: 'Self-Defense',
        description: 'Revolutionary armies',
      },
      {
        id: 'education',
        value: 20,
        name: 'Education',
        description: 'Limited access',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Destroyed',
      },
      {
        id: 'social-cohesion',
        value: 10,
        name: 'Social Cohesion',
        description: 'Civil war',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme poverty',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'Propaganda',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 90,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'War and famine',
      },
      {
        id: 'domestic-war-risk',
        value: 90,
        name: 'Domestic War Risk',
        description: 'Active civil war',
      },
    ],
    color: '#96CEB4',
  },
  {
    name: 'Great Depression',
    description: 'Global economic crash',
    historicalOutcome:
      'Breadlines form as factories close, unemployment reaches 25%, and public health deteriorates. The New Deal later brings some relief but recovery remains slow.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Mass unemployment',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Limited relief',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Civil unrest',
      },
      {
        id: 'education',
        value: 40,
        name: 'Education',
        description: 'Declining access',
      },
      {
        id: 'infrastructure',
        value: 30,
        name: 'Infrastructure',
        description: 'Neglected',
      },
      {
        id: 'social-cohesion',
        value: 40,
        name: 'Social Cohesion',
        description: 'Strained bonds',
      },
      {
        id: 'economic-inequality',
        value: 80,
        name: 'Economic Inequality',
        description: 'Extreme wealth gaps',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Free press',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 50,
        name: 'Political Corruption',
        description: 'Banking crisis',
      },
      {
        id: 'natural-disaster-frequency',
        value: 60,
        name: 'Natural Disaster Frequency',
        description: 'Dust Bowl',
      },
      {
        id: 'domestic-war-risk',
        value: 40,
        name: 'Domestic War Risk',
        description: 'Civil unrest',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Collapse of Venezuela',
    description: 'Modern hyperinflation crisis',
    historicalOutcome:
      'Economic mismanagement, corruption, and political instability lead to hyperinflation, mass emigration, and the collapse of public services.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 20,
        name: 'Domestic Manufacturing',
        description: 'Collapsed industry',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Failed state',
      },
      {
        id: 'self-defense',
        value: 60,
        name: 'Self-Defense',
        description: 'Civil unrest',
      },
      {
        id: 'education',
        value: 30,
        name: 'Education',
        description: 'Declining quality',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Collapsed',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Deep divides',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme poverty',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'State control',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'No innovation',
      },
      {
        id: 'corruption',
        value: 90,
        name: 'Political Corruption',
        description: 'Rampant corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Infrastructure failure',
      },
      {
        id: 'domestic-war-risk',
        value: 70,
        name: 'Domestic War Risk',
        description: 'High unrest',
      },
    ],
    color: '#4ECDC4',
  },
  {
    name: 'French Revolution',
    description: 'Inequality sparks revolt',
    historicalOutcome:
      'Widespread poverty and inequality lead to revolutionary violence. The monarchy falls, but the new republic faces internal conflict and external threats.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Agricultural economy',
      },
      {
        id: 'government-aid',
        value: 5,
        name: 'Government Aid',
        description: 'Minimal support',
      },
      {
        id: 'self-defense',
        value: 90,
        name: 'Self-Defense',
        description: 'Revolutionary violence',
      },
      {
        id: 'education',
        value: 15,
        name: 'Education',
        description: 'Elite only',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Poor roads',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Class divides',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme class divides',
      },
      {
        id: 'media-freedom',
        value: 30,
        name: 'Media Freedom',
        description: 'Revolutionary press',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 70,
        name: 'Political Corruption',
        description: 'Aristocratic privilege',
      },
      {
        id: 'natural-disaster-frequency',
        value: 50,
        name: 'Natural Disaster Frequency',
        description: 'Crop failures',
      },
      {
        id: 'domestic-war-risk',
        value: 90,
        name: 'Domestic War Risk',
        description: 'Revolution',
      },
    ],
    color: '#45B7D1',
  },
  {
    name: 'Industrial Revolution',
    description: 'Growth with social costs',
    historicalOutcome:
      'Massive economic growth but with severe social costs. Urban slums form, child labor is widespread, and environmental damage is extensive.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 90,
        name: 'Domestic Manufacturing',
        description: 'Massive growth',
      },
      {
        id: 'government-aid',
        value: 10,
        name: 'Government Aid',
        description: 'Little welfare',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Limited',
      },
      {
        id: 'education',
        value: 20,
        name: 'Education',
        description: 'Limited access',
      },
      {
        id: 'infrastructure',
        value: 60,
        name: 'Infrastructure',
        description: 'Industrial focus',
      },
      {
        id: 'social-cohesion',
        value: 30,
        name: 'Social Cohesion',
        description: 'Class divides',
      },
      {
        id: 'economic-inequality',
        value: 70,
        name: 'Economic Inequality',
        description: 'Growing gaps',
      },
      {
        id: 'media-freedom',
        value: 60,
        name: 'Media Freedom',
        description: 'Some freedom',
      },
      {
        id: 'research-development',
        value: 80,
        name: 'Research & Development',
        description: 'High innovation',
      },
      {
        id: 'corruption',
        value: 40,
        name: 'Political Corruption',
        description: 'Factory owner influence',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Industrial accidents',
      },
      {
        id: 'domestic-war-risk',
        value: 20,
        name: 'Domestic War Risk',
        description: 'Labor unrest',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Fall of Soviet Union',
    description: 'Socialist collapse',
    historicalOutcome:
      'Economic stagnation, political reforms, and nationalist movements lead to the dissolution of the Soviet Union and the end of the Cold War.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Declining output',
      },
      {
        id: 'government-aid',
        value: 30,
        name: 'Government Aid',
        description: 'Failing support',
      },
      {
        id: 'self-defense',
        value: 50,
        name: 'Self-Defense',
        description: 'Military decline',
      },
      {
        id: 'education',
        value: 50,
        name: 'Education',
        description: 'Quality decline',
      },
      {
        id: 'infrastructure',
        value: 30,
        name: 'Infrastructure',
        description: 'Neglected',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Nationalist divides',
      },
      {
        id: 'economic-inequality',
        value: 60,
        name: 'Economic Inequality',
        description: 'Growing gaps',
      },
      {
        id: 'media-freedom',
        value: 40,
        name: 'Media Freedom',
        description: 'Reform era',
      },
      {
        id: 'research-development',
        value: 30,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 80,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 30,
        name: 'Natural Disaster Frequency',
        description: 'Infrastructure failure',
      },
      {
        id: 'domestic-war-risk',
        value: 60,
        name: 'Domestic War Risk',
        description: 'Ethnic conflicts',
      },
    ],
    color: '#96CEB4',
  },
  {
    name: 'Post-WWII Boom',
    description: 'Post-war prosperity',
    historicalOutcome:
      'Economic growth, technological innovation, and social reforms create an era of unprecedented prosperity and stability in the Western world.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 80,
        name: 'Domestic Manufacturing',
        description: 'Industrial growth',
      },
      {
        id: 'government-aid',
        value: 60,
        name: 'Government Aid',
        description: 'Welfare state',
      },
      {
        id: 'self-defense',
        value: 40,
        name: 'Self-Defense',
        description: 'Stable security',
      },
      {
        id: 'education',
        value: 70,
        name: 'Education',
        description: 'Expanding access',
      },
      {
        id: 'infrastructure',
        value: 80,
        name: 'Infrastructure',
        description: 'Massive investment',
      },
      {
        id: 'social-cohesion',
        value: 70,
        name: 'Social Cohesion',
        description: 'Strong unity',
      },
      {
        id: 'economic-inequality',
        value: 40,
        name: 'Economic Inequality',
        description: 'Reduced gaps',
      },
      {
        id: 'media-freedom',
        value: 80,
        name: 'Media Freedom',
        description: 'Free press',
      },
      {
        id: 'research-development',
        value: 90,
        name: 'Research & Development',
        description: 'High innovation',
      },
      {
        id: 'corruption',
        value: 20,
        name: 'Political Corruption',
        description: 'Low corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 20,
        name: 'Natural Disaster Frequency',
        description: 'Low risk',
      },
      {
        id: 'domestic-war-risk',
        value: 10,
        name: 'Domestic War Risk',
        description: 'Low conflict',
      },
    ],
    color: '#4ECDC4',
  },
  {
    name: 'Roman Empire Fall',
    description: 'Ancient decline',
    historicalOutcome:
      'Internal decay, external pressures, and economic instability lead to the gradual collapse of the Roman Empire and the beginning of the Dark Ages.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 30,
        name: 'Domestic Manufacturing',
        description: 'Declining output',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Failing support',
      },
      {
        id: 'self-defense',
        value: 80,
        name: 'Self-Defense',
        description: 'Military strain',
      },
      {
        id: 'education',
        value: 25,
        name: 'Education',
        description: 'Declining literacy',
      },
      {
        id: 'infrastructure',
        value: 20,
        name: 'Infrastructure',
        description: 'Crumbling',
      },
      {
        id: 'social-cohesion',
        value: 20,
        name: 'Social Cohesion',
        description: 'Deep divides',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme gaps',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'State control',
      },
      {
        id: 'research-development',
        value: 10,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 80,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 40,
        name: 'Natural Disaster Frequency',
        description: 'Climate changes',
      },
      {
        id: 'domestic-war-risk',
        value: 90,
        name: 'Domestic War Risk',
        description: 'Constant civil wars',
      },
    ],
    color: '#FF6B6B',
  },
  {
    name: 'Ming Dynasty Collapse',
    description: 'Dynastic fall',
    historicalOutcome:
      'Internal corruption, peasant rebellions, and external pressures lead to the collapse of the Ming Dynasty and the rise of the Qing Dynasty.',
    factors: [
      {
        id: 'domestic-manufacturing',
        value: 40,
        name: 'Domestic Manufacturing',
        description: 'Declining output',
      },
      {
        id: 'government-aid',
        value: 20,
        name: 'Government Aid',
        description: 'Failing support',
      },
      {
        id: 'self-defense',
        value: 60,
        name: 'Self-Defense',
        description: 'Military decline',
      },
      {
        id: 'education',
        value: 30,
        name: 'Education',
        description: 'Limited access',
      },
      {
        id: 'infrastructure',
        value: 30,
        name: 'Infrastructure',
        description: 'Neglected',
      },
      {
        id: 'social-cohesion',
        value: 10,
        name: 'Social Cohesion',
        description: 'Severe unrest',
      },
      {
        id: 'economic-inequality',
        value: 90,
        name: 'Economic Inequality',
        description: 'Extreme gaps',
      },
      {
        id: 'media-freedom',
        value: 20,
        name: 'Media Freedom',
        description: 'State control',
      },
      {
        id: 'research-development',
        value: 20,
        name: 'Research & Development',
        description: 'Limited innovation',
      },
      {
        id: 'corruption',
        value: 90,
        name: 'Political Corruption',
        description: 'Widespread corruption',
      },
      {
        id: 'natural-disaster-frequency',
        value: 70,
        name: 'Natural Disaster Frequency',
        description: 'Severe climate changes',
      },
      {
        id: 'domestic-war-risk',
        value: 90,
        name: 'Domestic War Risk',
        description: 'Peasant rebellions',
      },
    ],
    color: '#4ECDC4',
  },
];

export interface HistoricalPreset {
  name: string;
  description: string;
  factors: Record<string, number>;
  color: string;
}

export const HISTORICAL_PRESETS: HistoricalPreset[] = [
  {
    name: 'Industrial Revolution',
    description:
      'Rapid industrialization with high pollution and social inequality',
    factors: {
      'domestic-manufacturing': 90,
      'government-aid': 20,
      healthcare: 30,
      education: 40,
      infrastructure: 70,
      'environmental-protection': 10,
      'tax-rate': 30,
      'media-freedom': 40,
      'self-defense': 60,
      'research-development': 80,
      corruption: 50,
      'social-cohesion': 40,
      'economic-inequality': 80,
      'technological-adoption': 90,
      'immigration-rate': 60,
      'natural-disaster-frequency': 30,
      'domestic-war-risk': 20,
    },
    color: '#FF6B6B',
  },
  {
    name: 'French Revolution',
    description: 'Social upheaval and political instability',
    factors: {
      'domestic-manufacturing': 40,
      'government-aid': 30,
      healthcare: 30,
      education: 50,
      infrastructure: 40,
      'environmental-protection': 20,
      'tax-rate': 70,
      'media-freedom': 60,
      'self-defense': 80,
      'research-development': 40,
      corruption: 70,
      'social-cohesion': 20,
      'economic-inequality': 80,
      'technological-adoption': 40,
      'immigration-rate': 30,
      'natural-disaster-frequency': 20,
      'domestic-war-risk': 90,
    },
    color: '#4ECDC4',
  },
  {
    name: 'Post-WWII Boom',
    description: 'Economic growth and social welfare expansion',
    factors: {
      'domestic-manufacturing': 80,
      'government-aid': 70,
      healthcare: 70,
      education: 80,
      infrastructure: 80,
      'environmental-protection': 40,
      'tax-rate': 50,
      'media-freedom': 70,
      'self-defense': 60,
      'research-development': 70,
      corruption: 30,
      'social-cohesion': 70,
      'economic-inequality': 40,
      'technological-adoption': 90,
      'immigration-rate': 50,
      'natural-disaster-frequency': 20,
      'domestic-war-risk': 10,
      'mana-storm-intensity': 10,
      'thanos-snap-probability': 5,
      'godzilla-rampage': 5,
    },
    color: '#45B7D1',
  },
  {
    name: 'Collapse of Venezuela',
    description: 'Economic collapse and social unrest',
    factors: {
      'domestic-manufacturing': 20,
      'government-aid': 30,
      healthcare: 20,
      education: 30,
      infrastructure: 30,
      'environmental-protection': 40,
      'tax-rate': 60,
      'media-freedom': 20,
      'self-defense': 40,
      'research-development': 20,
      corruption: 90,
      'social-cohesion': 20,
      'economic-inequality': 90,
      'technological-adoption': 30,
      'immigration-rate': 5,
      'natural-disaster-frequency': 40,
      'domestic-war-risk': 70,
      'mana-storm-intensity': 30,
      'thanos-snap-probability': 20,
      'godzilla-rampage': 10,
    },
    color: '#96CEB4',
  },
  {
    name: 'Fall of the Soviet Union',
    description: 'Political collapse and economic transition',
    factors: {
      'domestic-manufacturing': 40,
      'government-aid': 30,
      healthcare: 30,
      education: 50,
      infrastructure: 40,
      'environmental-protection': 20,
      'tax-rate': 50,
      'media-freedom': 60,
      'self-defense': 40,
      'research-development': 40,
      corruption: 80,
      'social-cohesion': 30,
      'economic-inequality': 70,
      'technological-adoption': 50,
      'immigration-rate': 40,
      'natural-disaster-frequency': 30,
      'domestic-war-risk': 60,
      'mana-storm-intensity': 20,
      'thanos-snap-probability': 15,
      'godzilla-rampage': 5,
    },
    color: '#FFEEAD',
  },
];

export const PRESET_COLORS = {
  'Industrial Revolution': '#FF6B6B',
  'French Revolution': '#4ECDC4',
  'Post-WWII Boom': '#45B7D1',
  'Collapse of Venezuela': '#96CEB4',
  'Fall of the Soviet Union': '#FFEEAD',
  'Anarchic Society': '#FF6B6B',
  'Viking Society': '#4ECDC4',
  'Barter Society': '#45B7D1',
  'Feudal Society': '#96CEB4',
  'Technocratic Society': '#FFEEAD',
  'Nomadic Society': '#D4A5A5',
  'Balanced Society': '#FF6B6B',
  'Lower Class Focus': '#4ECDC4',
  'Middle Class Focus': '#45B7D1',
  'Upper Class Focus': '#FFEEAD',
  'Militant Society': '#FF6B6B',
  'Socialist State': '#D4A5A5',
  'Great Depression': '#8B4513', // Changed to a brown color to represent economic hardship
  'Roman Empire Fall': '#FF6B6B',
  'Ming Dynasty Collapse': '#4ECDC4',
  'Pre-Revolutionary Iran': '#FF6B6B',
  'Weimar Republic': '#4ECDC4',
  'Pre-Civil War America': '#45B7D1',
  'Pre-Communist China': '#96CEB4',
};
